### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by DMagic1** [MagicSmokeIndustries/IR-Surface-Sampler#3]
There have a been a few changes to how science experiments work in 1.0.

It is now possible to activate experiments while on EVA and it is possible to specify requirements for activating experiments, both on EVA and while controlling the vessel. 

Most stock parts allow any vessel you are in control of to activate an experiment, but only scientists to activate it on EVA.

Should I follow this convention? It is possible to allow for any Kerbal to activate from EVA, or to not allow it at all.

**Comment by erendrake** [comment]
I would allow it, it feels pretty kerbal to have the dang thing not work and have someone get out and hit it with a hammer

**Comment by ZodiusInfuser** [comment]
Sounds like a good idea. Does seem redundant though considering its the same surface sample as kerbals, but should be made like that for consistency.

What sort of requirements can be added?

**Comment by DMagic1** [comment]
In stock you can specify that it must be a scientist or just any Kerbal. But it's also very easy to add a level requirement as well. I suppose I could also make it require an engineer, but I figure it's probably best just to allow any Kerbal to do it.

**Comment by ZodiusInfuser** [comment]
Go for allowing any kerbal to do it, even if they can take their own samples.

**Comment by erendrake** [comment]
I agree, since it is a duplication of a tool that each kerbal already has there is no 'cheating' that we are enabling by letting everyone use it.

**Comment by DMagic1** [comment]
I merged this; any Kerbal should be able to deploy the experiment on EVA.

**Comment by erendrake** [comment]
@DMagic1 sweet, that looks good, sorry it a little slow going these days. thank you for working on that.
